# Generated by Django 3.0.7 on 2020-06-29 21:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Developer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('founder', models.CharField(max_length=18)),
                ('date_of_establishment', models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Engine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('programming_language', models.CharField(max_length=30)),
                ('release_date', models.DateField(null=True)),
                ('developer', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Plattform',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('specs', models.TextField()),
                ('description', models.TextField(null=True)),
                ('portable', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=18)),
                ('year_revenue', models.IntegerField()),
                ('developer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.Developer')),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('genre', models.CharField(max_length=30)),
                ('release_date', models.DateField(null=True)),
                ('cover', models.ImageField(null=True, upload_to='')),
                ('description', models.TextField(null=True)),
                ('hardware_requirements', models.TextField(null=True)),
                ('rating', models.FloatField()),
                ('multyplayer', models.BooleanField(default=False)),
                ('crossplay', models.BooleanField(default=False)),
                ('sales', models.IntegerField(null=True)),
                ('engine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.Engine')),
                ('plattform', models.ManyToManyField(to='Games.Plattform')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.Publisher')),
            ],
        ),
    ]
