# Generated by Django 3.0.7 on 2020-06-29 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='developer',
            name='founder',
        ),
        migrations.AddField(
            model_name='developer',
            name='management',
            field=models.CharField(max_length=18, null=True),
        ),
    ]
