# Generated by Django 3.0.7 on 2020-06-29 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0002_auto_20200629_2332'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='developer',
        ),
        migrations.AddField(
            model_name='publisher',
            name='developer',
            field=models.ManyToManyField(to='Games.Developer'),
        ),
    ]
