# Generated by Django 3.0.7 on 2020-06-29 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0004_auto_20200629_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='name',
            field=models.CharField(default='DEBUG', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='plattform',
            name='name',
            field=models.CharField(default='DEBUG', max_length=18),
            preserve_default=False,
        ),
    ]
