# Generated by Django 3.0.7 on 2020-06-29 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0005_auto_20200629_2343'),
    ]

    operations = [
        migrations.RenameField(
            model_name='game',
            old_name='multyplayer',
            new_name='multiplayer',
        ),
        migrations.AlterField(
            model_name='developer',
            name='date_of_establishment',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='developer',
            name='management',
            field=models.CharField(blank=True, max_length=18, null=True),
        ),
        migrations.AlterField(
            model_name='engine',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='game',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='hardware_requirements',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='game',
            name='sales',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='plattform',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
