# Generated by Django 3.0.7 on 2020-06-29 22:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0006_auto_20200630_0005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='game',
            name='plattform',
        ),
    ]
