# Generated by Django 3.0.7 on 2020-06-30 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0008_game_plattform'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='usk',
            field=models.IntegerField(default=16),
            preserve_default=False,
        ),
    ]
