# Generated by Django 3.0.7 on 2020-06-30 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0009_game_usk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='engine',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Games.Engine'),
        ),
    ]
