# Generated by Django 3.0.7 on 2020-06-30 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0010_auto_20200630_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='developer',
            field=models.ManyToManyField(to='Games.Developer'),
        ),
    ]
