# Generated by Django 3.0.7 on 2020-06-30 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0011_game_developer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='publisher',
            name='year_revenue',
        ),
        migrations.AddField(
            model_name='publisher',
            name='year_revenue_in_mrd',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
