# Generated by Django 3.0.7 on 2020-07-05 19:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0012_auto_20200630_1323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='cover',
            field=models.ImageField(blank=True, null=True, upload_to='templates/static/images'),
        ),
        migrations.AlterField(
            model_name='game',
            name='engine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Games.Engine'),
        ),
        migrations.AlterField(
            model_name='game',
            name='usk',
            field=models.CharField(choices=[(0, 0), (6, 6), (12, 12), (16, 16), (18, 18)], default=0, max_length=2),
        ),
    ]
