# Generated by Django 3.0.7 on 2020-07-05 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0013_auto_20200705_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='usk',
            field=models.CharField(choices=[('0', 0), ('6', 6), ('12', 12), ('16', 16), ('18', 18)], default='0', max_length=2),
        ),
    ]
