# Generated by Django 3.0.7 on 2020-07-14 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Games', '0018_genre_empty'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='empty',
        ),
    ]
